services:
  - type: static_site
    name: inventario-inteligente
    buildCommand: npm install && npm run build
    publishDir: dist/inventarioIAFrontEnd/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html