services:
  - type: static_site
    name: inventario-inteligente
    buildCommand: echo "========== RENDER.YAML LEIDO ==========" && echo "INICIANDO BUILD..." && exit 1
    publishDir: dist/inventarioIAFrontEnd/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html